# Bucles

- while

In [2]:
# ojo que si no para petamos el pc

x=0

while x<10:
    x=x+1
    print(x)

1
2
3
4
5
6
7
8
9
10


- for

In [10]:
y=[1,2,3,4,5]

for i in y:
    print (i)
    

1
2
3
4
5


- for loop (enumerate)

In [12]:
# este enumerate permite sacar el índice
for index,i in enumerate (y):
    print(index,i)

0 1
1 2
2 3
3 4
4 5


In [21]:
# construyendo una frase
for index,i in enumerate (y):
    print("Índice" ,index,":", i)

Índice 0 : 1
Índice 1 : 2
Índice 2 : 3
Índice 3 : 4
Índice 4 : 5


In [23]:
# o la que sale en la teoría
for index,i in enumerate (y):
    print("Índice " +str(index)+":", str(i))

Índice 0: 1
Índice 1: 2
Índice 2: 3
Índice 3: 4
Índice 4: 5


In [24]:
for x in "Hola Mundo":
    print(x.capitalize())

H
O
L
A
 
M
U
N
D
O


# Listas

In [32]:
paises=["China","India","Estados Unidos","Indonesia","Brasil"]
poblaciones= [1.38,1.29,0.33,0.26,0.20]
poblacionex =[["China",1.38],["India",1.29],["Estados Unidos",0.33],["Indonesia",0.26],["Brasil",0.20]]

In [33]:
poblacionex

[['China', 1.38],
 ['India', 1.29],
 ['Estados Unidos', 0.33],
 ['Indonesia', 0.26],
 ['Brasil', 0.2]]

In [46]:
#for loop
for x in poblacionex:
    print ("La población de " + x[0] + "es de "+ str(x[1])+ "mil millones")

La población de Chinaes de 1.38mil millones
La población de Indiaes de 1.29mil millones
La población de Estados Unidoses de 0.33mil millones
La población de Indonesiaes de 0.26mil millones
La población de Brasiles de 0.2mil millones


## Diferentes estructuras de datos 

- Diccionarios usa el metodo mi_dicc.items() 
- Matriz numpy utiliza la función np.inder(mi_matriz)

In [51]:
mi_dicc= {"China":1.38, "India":1.29, "Estados Unidos":0.33, "Indonesia":0.26, "Brasil":0.20}

In [52]:
mi_dicc

{'China': 1.38,
 'India': 1.29,
 'Estados Unidos': 0.33,
 'Indonesia': 0.26,
 'Brasil': 0.2}

In [55]:
#for loop
# cómo hacer lo mismo que antes utilizando un diccionario (antes era listas dentro de listas)
#k = llave(china) v = valor
for k,v in mi_dicc.items():
    print ("la población de "+ k+ " es de "+ str(v)+ " miles de millones")
    

la población de China es de 1.38 miles de millones
la población de India es de 1.29 miles de millones
la población de Estados Unidos es de 0.33 miles de millones
la población de Indonesia es de 0.26 miles de millones
la población de Brasil es de 0.2 miles de millones


In [56]:
# for loop con numpy
peso= [45,55,65] 
alturas= [1.50,1.65,1.71]
np_peso= np.array(peso)
np_alturas= np.array(alturas)
np_bmi= np_peso / (np_alturas **2)

In [59]:
bmi=np_bmi
bmi

array([20.        , 20.2020202 , 22.22906193])

In [60]:
for x in bmi:
    print(x)

20.0
20.202020202020204
22.229061933586404


In [62]:
#que pasa en una matriz 2d
altura_peso= np.array([np_peso,np_alturas])

In [63]:
altura_peso

array([[45.  , 55.  , 65.  ],
       [ 1.5 ,  1.65,  1.71]])

In [64]:
#pasa que esto no es un loop
for x in altura_peso:
    print (x)

[45. 55. 65.]
[1.5  1.65 1.71]


In [65]:
#tenemos que cambiar con np.inditer
for x in np.nditer(altura_peso):
    print (x)


45.0
55.0
65.0
1.5
1.65
1.71


# Pandas dataframe

In [67]:
import pandas as pd
paises=["China","India","Estados Unidos","Indonesia","Brasil"]
poblaciones= [1.38,1.29,0.33,0.26,0.20]
mi_dicc = { "Países": paises, "Población": poblaciones}
Población = pd.DataFrame(mi_dicc)
Población

Países  Población
0           China       1.38
1           India       1.29
2  Estados Unidos       0.33
3       Indonesia       0.26
4          Brasil       0.20

In [76]:
for i in Población:
    print (i)

Países
Población


In [78]:
Población.index= ["CN","IN","US","ID","BR"]
for etiqueta, fila in Población.iterrows():
    print(etiqueta)
    print(fila)

CN
Países       China
Población     1.38
Name: CN, dtype: object
IN
Países       India
Población     1.29
Name: IN, dtype: object
US
Países       Estados Unidos
Población              0.33
Name: US, dtype: object
ID
Países       Indonesia
Población         0.26
Name: ID, dtype: object
BR
Países       Brasil
Población       0.2
Name: BR, dtype: object


In [80]:
for etiqueta, fila in Población.iterrows():
    print(etiqueta + " : "+ fila["Países"])


CN : China
IN : India
US : Estados Unidos
ID : Indonesia
BR : Brasil


In [82]:
for etiqueta, fila in Población.iterrows():
    print(etiqueta + " : "+ str(fila["Población"]))

CN : 1.38
IN : 1.29
US : 0.33
ID : 0.26
BR : 0.2


In [8]:
# se pueden utilizar para AÑADIR COLUMNAS
import pandas as pd
paises=["China","India","Estados Unidos","Indonesia","Brasil"]
poblaciones= [1.38,1.29,0.33,0.26,0.20]
mi_dicc = { "Países": paises, "Población": poblaciones}
Población = pd.DataFrame(mi_dicc)
for etiqueta, fila in Población.iterrows():

#aquí está el codigo ".loc"
    Población.loc[etiqueta, "largo"]= len(fila["Países"])
    print (Población)

           Países  Población  largo
0           China       1.38    5.0
1           India       1.29    NaN
2  Estados Unidos       0.33    NaN
3       Indonesia       0.26    NaN
4          Brasil       0.20    NaN
           Países  Población  largo
0           China       1.38    5.0
1           India       1.29    5.0
2  Estados Unidos       0.33    NaN
3       Indonesia       0.26    NaN
4          Brasil       0.20    NaN
           Países  Población  largo
0           China       1.38    5.0
1           India       1.29    5.0
2  Estados Unidos       0.33   14.0
3       Indonesia       0.26    NaN
4          Brasil       0.20    NaN
           Países  Población  largo
0           China       1.38    5.0
1           India       1.29    5.0
2  Estados Unidos       0.33   14.0
3       Indonesia       0.26    9.0
4          Brasil       0.20    NaN
           Países  Población  largo
0           China       1.38    5.0
1           India       1.29    5.0
2  Estados Unidos       0.33

### Apply para acortar codigo de bucles

In [13]:
# SE PUEDE HACER TODO EN UNA LINEA CON LA FUNCIÓN APPLY MUCHO MÁS RAPIDO QUE ITERROWS

In [14]:
Población["largo_apply"] = Población["Países"].apply(len)

In [15]:
Población

Países  Población  largo  largo_apply
0           China       1.38    5.0            5
1           India       1.29    5.0            5
2  Estados Unidos       0.33   14.0           14
3       Indonesia       0.26    9.0            9
4          Brasil       0.20    6.0            6