# Introducción a Numpy

In [3]:
import numpy as np

In [ ]:
# Alternativa a "listas", se utilizan "matrices"


In [4]:
peso= [45,55,65]
alturas= [1.50,1.65,1.71]

In [5]:
bmi= peso/ alturas ** 2
# no podemos dividir una lista entre otra lista

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [7]:
np_peso= np.array(peso)
np_alturas= np.array(alturas)
np_bmi= np_peso / (np_alturas **2)

In [8]:
np_bmi

array([20.        , 20.2020202 , 22.22906193])

In [9]:
# Se puede dividir listas entre sí con numpy
# Cada matriz de numpy tiene que ser solo de Un tipo

In [10]:
prueba = np.array ([1.5,"dos", True])
prueba

array(['1.5', 'dos', 'True'], dtype='<U32')

In [11]:
#acaba de convertir todos los objetos a str : Coherción

## Suma con matrices ( Numpy)

In [12]:
list= [1,2,3]
list + list
# concatena list

[1, 2, 3, 1, 2, 3]

In [13]:
#pasamos a matriz la list
lista = np.array(list)
lista + lista
#suma los elementos de "lista"

array([2, 4, 6])

In [14]:
#podemos extraer elementos de matrices también
lista [1]

2

In [15]:
# o que cumplan condiciones
lista > 2

array([False, False,  True])

In [16]:
lista [:1]

array([1])

In [17]:
lista [1:]

array([2, 3])

## Matrices 2d

In [18]:
#crear una matriz con 2 dimensiones ( 2 filas)
np_2d = np.array([peso,alturas])
np_2d

array([[45.  , 55.  , 65.  ],
       [ 1.5 ,  1.65,  1.71]])

In [19]:
# para ver el numero de filas y columnas
np_2d.shape
#2 filas, 3 columnas

(2, 3)

In [20]:
#para extraer elementos es como si fuera una dentro de otra
np_2d [0][1]

55.0

In [21]:
# se puede hacer también de la siguiente forma 
np_2d [0,1]

55.0

In [22]:
#para coger todos los elementos se hace igual que en listas
np_2d [1,:]

array([1.5 , 1.65, 1.71])

In [23]:
#mas rapido
np_2d[1]

array([1.5 , 1.65, 1.71])

In [24]:
#para varias filas
np_2d [0:2,0:2]

array([[45.  , 55.  ],
       [ 1.5 ,  1.65]])

# Estadística con numpy

In [25]:
#podemos crear nuestros propios datos 
# np.random.normal  = datos.aleatorios.distribucion normal
# np.random.normal(valor, desviacion estandar, cantidad de datos)
# altura_1000= np.random.normal(1.70,0.2,1000)
# salen muchos decimales, redondeamos con NP.round(np...., 2 digitos)
altura_1000= np.round(np.random.normal(1.70,0.2,1000),2)

In [26]:
altura_1000

array([2.01, 1.47, 1.42, 2.16, 1.76, 1.26, 1.75, 1.33, 1.62, 1.81, 1.79,
       1.55, 1.59, 1.92, 1.36, 1.71, 1.79, 1.63, 1.69, 1.97, 1.66, 1.57,
       1.84, 1.82, 1.67, 1.52, 1.68, 1.54, 1.98, 1.5 , 1.51, 1.63, 1.69,
       1.8 , 1.83, 1.63, 1.81, 1.95, 1.48, 1.5 , 1.77, 1.84, 1.92, 1.65,
       1.71, 1.77, 1.24, 1.4 , 1.96, 2.02, 1.48, 1.92, 1.68, 1.5 , 1.52,
       2.01, 1.35, 1.56, 1.69, 1.86, 1.95, 1.77, 1.89, 1.77, 1.98, 1.5 ,
       1.48, 1.74, 1.78, 1.69, 1.79, 1.73, 1.65, 1.56, 2.01, 1.56, 1.43,
       1.73, 1.79, 1.67, 1.65, 1.66, 1.47, 1.84, 1.82, 1.93, 1.73, 1.59,
       1.54, 1.89, 2.12, 1.88, 2.04, 1.78, 1.51, 1.51, 1.78, 1.66, 1.64,
       1.49, 1.58, 1.73, 1.79, 2.13, 1.88, 2.09, 1.94, 1.01, 1.54, 1.72,
       1.92, 1.97, 1.88, 1.57, 1.88, 1.86, 1.55, 1.68, 1.67, 1.64, 1.64,
       1.85, 1.31, 1.83, 2.12, 1.74, 1.51, 1.57, 1.95, 1.13, 1.91, 1.91,
       1.6 , 1.59, 1.93, 1.86, 1.84, 1.61, 1.88, 1.26, 1.5 , 1.45, 1.6 ,
       2.05, 1.74, 2.  , 1.86, 1.63, 1.86, 1.64, 1.

In [27]:
?np.random.normal
#tambien podemos hacer que la cantidad sea una matriz (n,n) con size= (n,n)
#medimos con shape

In [28]:
altura_1000.shape

(1000,)

In [29]:
peso_1000= np.round(np.random.normal(58,8,1000),2)

In [30]:
peso_1000.shape

(1000,)

In [31]:
#agrupamos las matrices en relacion 1:1 con "column_stack"
datos_1000= np.column_stack((altura_1000,peso_1000))

In [32]:
datos_1000.shape

(1000, 2)

In [33]:
datos_1000
#para cada altura nos da 1 peso, dan 1000 datos, 2 infos de cada (1000,2)

array([[ 2.01, 49.99],
       [ 1.47, 78.06],
       [ 1.42, 63.28],
       ...,
       [ 1.77, 49.48],
       [ 1.68, 60.67],
       [ 1.65, 64.32]])

In [34]:
#empezamos a usar estadistica
#media
np.mean(datos_1000[:,0])

1.70389

In [35]:
#acabamos de extraer todos los elementos ":" de altura "[0]"

In [36]:
#mediana
np.median(datos_1000[:,0])

1.7

In [37]:
#coeficiente de correlación
np.corrcoef(datos_1000[:,0])

1.0

In [38]:
#aqui vemos que casi no hay correlacion (lejos de 1 o -1)
np.corrcoef(datos_1000[:,0], datos_1000[:,1])

array([[1.        , 0.03717181],
       [0.03717181, 1.        ]])

In [39]:
 #desviacion estandar
np.std(datos_1000[:,0])

0.20018683248405725