# Lógica en Python

In [1]:
# Logica , comparadores y resultados Boolean mas utilizados

In [2]:
import numpy as np

In [3]:
bmi= np.array([21.4,22.9,23.1,21.2])

In [4]:
bmi >23

array([False, False,  True, False])

In [5]:
# si queremos solo los True
bmi [bmi >23]

array([23.1])

In [6]:
3<5

True

In [7]:
#se usa doble=
3==5

False

In [8]:
3>=5

False

In [9]:
# diferente de 
3!=5

True

In [11]:
#orden alfabetico (No longitud)
# alejandro está antes que alex
"alejandro"< "alex"

True

## not

In [12]:
not True

False

In [13]:
not False

True

## Logical Numpy

In [14]:
bmi

array([21.4, 22.9, 23.1, 21.2])

In [15]:
bmi >23

array([False, False,  True, False])

In [16]:
bmi <25

array([ True,  True,  True,  True])

In [17]:
# da error, no es logico para numpy
bmi >23 and <25

SyntaxError: invalid syntax (Temp/ipykernel_10288/3346254677.py, line 1)

Hay tres funciones logicas:
- logical_and()
- logical_or()
- logical_not()

In [18]:
#logical_and
np.logical_and(bmi>23,bmi<25)

array([False, False,  True, False])

In [20]:
#para escoger esos valores True
bmi[np.logical_and(bmi>23,bmi<25)]

array([23.1])

## Operadores Boolean

Hay tres: 
- and
- or
- not

### con AND tienen que ser los 2 verdaderos para que salga verdadero

In [21]:
False and True

False

In [22]:
False and False

False

In [23]:
True and True

True

### or: por lo menos 1 es verdad

In [28]:
True or False

True

In [29]:
False or False

False

### not: la inversa

In [30]:
not True

False

In [31]:
not False

True

# if , else, elif

In [57]:
x=3

In [58]:
#Si ( si no ponemos si no" y no se cumple, no actúa)

In [59]:
if x>2: 
    print ("X es mayor que 2")

X es mayor que 2


In [60]:
#Si, si no..

In [61]:
if x>2: 
    print ("X es mayor que 2")
else: 
    print ("X no es mayor que 2")

X es mayor que 2


In [64]:
# elif puedes usar mas condiciones
x=-6
if x>2: 
    print ("X es mayor que 2")
elif x<-2:
    print ("X es menor que -2")
else: 
    print ("X no es mayor que 2")

#OJO, si cumple elif, ya no actúa else
# else solo actúa si ninguno es cierto

X es menor que -2


# Extrayendo datos de un DataFrame ( con lógica)

In [65]:
import pandas as pd

In [67]:
paises= ["China","India","Estados Unidos","Indonesia","Brasil"]
poblaciones = [1.38,1.29,0.33,0.26,0.20]
mi_dicc= {"Países": paises, "Población":poblaciones}
Población= pd.DataFrame(mi_dicc)
Población.index= ["CN","IN","US","ID","BR"]

In [68]:
Población

Países  Población
CN           China       1.38
IN           India       1.29
US  Estados Unidos       0.33
ID       Indonesia       0.26
BR          Brasil       0.20

In [69]:
Población[["Población"]]

Población
CN       1.38
IN       1.29
US       0.33
ID       0.26
BR       0.20

In [70]:
Población.loc[:,"Población"]

CN    1.38
IN    1.29
US    0.33
ID    0.26
BR    0.20
Name: Población, dtype: float64

In [71]:
Población.iloc[:,1]

CN    1.38
IN    1.29
US    0.33
ID    0.26
BR    0.20
Name: Población, dtype: float64

In [72]:
# Despues del respaso anterior
# Qué países tienen población >1?
Población["Población"]>1

CN     True
IN     True
US    False
ID    False
BR    False
Name: Población, dtype: bool

In [74]:
# coger solo True
Población[Población["Población"]>1]

Países  Población
CN  China       1.38
IN  India       1.29

In [75]:
#la otra forma sería poner los resultados en una nueva variable
poblados= Población["Población"]>1
Población[poblados]

Países  Población
CN  China       1.38
IN  India       1.29

In [81]:
# si queremos coger entre varios valores
#usar np.logical_and


In [89]:
np.logical_and(Población["Población"] > 0.2,Población["Población"] < 0.5)


CN    False
IN    False
US     True
ID     True
BR    False
Name: Población, dtype: bool

In [90]:
Pueblitos= np.logical_and(Población["Población"] > 0.2,Población["Población"] < 0.5)
Población[Pueblitos]

Países  Población
US  Estados Unidos       0.33
ID       Indonesia       0.26